version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         # docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker run --detach --name wip alpine:latest
         docker exec sh -c 'apk add packer qemu'
