version: 2
jobs:
 build:
   machine: true
   environment:
     IMAGE_TAG: jupytercloud-project/build-container:latest
     ARTIFACT_DIR: ./artifacts
     ARTIFACT_NAME: jupytercloud-project_build-container_latest
     HGR: github.com/tcnksm/ghr
     RELEASE_VERSION: 0.0.1
   steps:
     - attach_workspace:
         at: ${ARTIFACT_DIR}
     - checkout
     - run: 
         name: "Building docker image"
         command: |
           docker image build \
                  --compress \
                  --tag ${IMAGE_TAG} \
                  --file Dockerfile \
                  .
     - run: docker image ls --all
     - run:
         name: "Saving docker image"
         command: |
           docker image save ${IMAGE_TAG} > ${ARTIFACT_NAME}.tar
           gzip ${ARTIFACT_NAME}.tar
           mv ${ARTIFACT_NAME}.tar.gz ${ARTIFACT_DIR}
     #
     # https://github.com/tcnksm/ghr
     #

     - run:
         name: "Publishing release on GitHub"
         command: |
           go get ${GHR}
           VERSION=
           ghr -t ${GITHUB_TOKEN} \
               -u ${CIRCLE_PROJECT_USERNAME} \
               -r ${CIRCLE_PROJECT_REPONAME} \
               -c ${CIRCLE_SHA1} \
               -delete ${RELEASE_VERSION} \
               ${ARTIFACT_DIR}
         
