version: 2
jobs:
 build:
   machine: true
   environment:
     IMAGE_NAME: wip
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     #- run: docker run --name $IMAGE_NAME --detach --interactive --rm alpine:latest sh
     #- run: docker exec $IMAGE_NAME sh -c 'apk update'
     #- run: docker exec $IMAGE_NAME sh -c 'apk add qemu'
     #- run: docker image ls --all
     - run: docker build --force-rm --compress .
     #- run: docker build --force-rm --compress --tag jupytercloud-project/build-container:latest .
     - run: docker image ls --all
