version: 2
jobs:
 build:
   machine: true
   environment:
     IMAGE_NAME: wip
   steps:
     - checkout
     - run: 
         name: "Building docker image"
         command: |
           docker image build \
                  --compress \
                  --tag jupytercloud-project/build-container:latest \
                  --file Dockerfile \
                  .
     - run: docker image ls --all
     - run:
         name: "Saving docker image"
         command: |
           docker image save jupytercloud-project/build-container:latest | tar -cvzf jupytercloud-project_build-container_latest.tgz
     #
     # https://github.com/tcnksm/ghr
     #
     - attach_workspace:
         at: ./artifacts
     - run:
         name: "Publishing release on GitHub"
         command: |
           go get github.com/tcnksm/ghr
           VERSION="0.0.1"
           ghr -t ${GITHUB_TOKEN} \
               -u ${CIRCLE_PROJECT_USERNAME} \
               -r ${CIRCLE_PROJECT_REPONAME} \
               -c ${CIRCLE_SHA1} \
               -delete ${VERSION} \
               ./artifacts/
         
